FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt.
RUN pip install --no-cache-dir -r requirements.txt

COPY..

# Run with gunicorn, bind 0.0.0.0:8000, 2 workers is fine for t2.micro/t3.micro
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:8000", "app:app"]